---
- name: Detectar pods caídos en OpenShift
  hosts: localhost
  sources:
    - name: Obtener estado de los pods
      ansible.eda.generic:
        module: kubernetes.core.k8s_info
        kind: Pod
        namespace: aap
  rules:
    - name: Detectar pod en estado de error
      condition: event.resources | selectattr('status.phase', 'in', ['Failed', 'CrashLoopBackOff']) | list | length > 0
      action:
        run_playbook:
          name: alertar_pod_caido.yml
