---
- name: Detectar cambios en un archivo
  hosts: all
  sources:
    - name: watch_for_changes
      ansible.eda.file_watch:
        paths:
          - /tmp/testfile
  rules:
    - name: Notificar cambio de archivo
      condition: event.path is defined
      action:
        run_job_template:
          name: notify.yml
